# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('senders', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_id', models.CharField(blank=True, default='', max_length=1024)),
                ('summary', models.TextField(blank=True, default='')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accounts', models.ManyToManyField(blank=True, help_text='The accounts this event belongs to. A event will be sent to all accounts granted to each of their accounts.', related_name='event_set', related_query_name='account', to='accounts.Account', verbose_name='accounts')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_events', to='senders.Sender')),
            ],
            options={
                'db_table': 'events',
                'ordering': ('start', 'end', 'sender'),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('id',)]),
        ),
    ]
