# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='calendar_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
