# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_recurrence_ends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='ends',
            field=models.CharField(blank=True, choices=[('On', 'On'), ('After', 'After')], default='Never', max_length=10),
        ),
    ]
