# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190807_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='override',
            name='reminder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='events.Reminder'),
        ),
    ]
