# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190731_0739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'managed': True, 'ordering': ('start', 'end', 'creator')},
        ),
    ]
