# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 11:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190807_1137'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='override',
            table='override',
        ),
    ]
