# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 20:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190808_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='until',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
