# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190808_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='ends',
            field=models.CharField(choices=[('Never', 'Never'), ('On', 'On'), ('After', 'After')], default='Never', max_length=10),
        ),
    ]
