# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20190807_1153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='override',
            options={'managed': True, 'ordering': ('id',)},
        ),
        migrations.AlterUniqueTogether(
            name='override',
            unique_together=set([('id',)]),
        ),
    ]
