# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190808_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='freq',
            field=models.CharField(choices=[('DAILY', 'days'), ('WEEKLY', 'weeks'), ('MONTHLY', 'monthds'), ('MONTHLY', 'years')], default='DAILY', max_length=10),
        ),
    ]
