# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-07 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190807_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='use_default',
            new_name='useDefault',
        ),
    ]
