# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20190808_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrence',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrences', to='events.Event'),
        ),
    ]
