# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20190808_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='calendar_event_id',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
