# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_calendar_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='calendar_id',
        ),
    ]
