# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_calendar_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_event_id', models.CharField(max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'calendar_event',
                'ordering': ('created_at',),
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendar_event_id',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_event_events', to='events.Event'),
        ),
        migrations.AlterUniqueTogether(
            name='calendarevent',
            unique_together=set([('id', 'calendar_event_id')]),
        ),
    ]
