# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 06:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
