# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-04 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0002_auto_20190903_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='application_name',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
