# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 13:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0003_auto_20190731_0809'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'managed': True},
        ),
    ]
