# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-31 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0004_auto_20190731_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sender',
            options={'managed': True, 'ordering': ('id',)},
        ),
    ]
