# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0004_auto_20190904_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='token_expiry',
            field=models.DateTimeField(blank=True),
        ),
    ]
