# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0005_auto_20190905_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='token_expiry',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
