# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0006_auto_20190905_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2token',
            name='code',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
