# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0007_oauth2token_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='access_token',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='code',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='oauth2token',
            name='refresh_token',
            field=models.CharField(default='', max_length=254),
        ),
    ]
