# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0008_auto_20190905_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauth2token',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
