# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-05 02:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0009_oauth2token_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauth2token',
            name='token_expiry',
            field=models.CharField(default='', max_length=254),
        ),
    ]
