# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-07 03:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('senders', '0010_auto_20190905_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sender',
            name='application_name',
        ),
    ]
