# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-08 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ('email',),
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=set([('email', 'id')]),
        ),
    ]
