# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-01 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': True, 'ordering': ('email',)},
        ),
    ]
